/*****< hci_constants.h >******************************************************/
/*      Copyright 2000 - 2014 Stonestreet One.                                */
/*      All Rights Reserved.                                                  */
/*                                                                            */
/*  HCITYPES - Bluetooth HCI Type Definitions/Constants.                      */
/*                                                                            */
/*  Author:  Damon Lange                                                      */
/*                                                                            */
/*** MODIFICATION HISTORY *****************************************************/
/*                                                                            */
/*   mm/dd/yy  F. Lastname    Description of Modification                     */
/*   --------  -----------    ------------------------------------------------*/
/*   08/25/00  D. Lange       Initial creation.                               */
/*   12/07/07  D. Mason       Changes for BT 2.1                              */
/******************************************************************************/
#ifndef _HCI_CONSTANTSH
#define _HCI_CONSTANTSH

#include <stdint.h>

typedef enum
{
   ptHCICommandPacket = 0x01,           /* Simple HCI Command Packet    */
                                        /* Type.                        */
   ptHCIACLDataPacket = 0x02,           /* HCI ACL Data Packet Type.    */
   ptHCISCODataPacket = 0x03,           /* HCI SCO Data Packet Type.    */
   ptHCIeSCODataPacket= 0x03,           /* HCI eSCO Data Packet Type.   */
   ptHCIEventPacket   = 0x04,           /* HCI Event Packet Type.       */
   ptHCIAdditional    = 0x05            /* Starting Point for Additional*/
                                        /* HCI Packet Types that are    */
                                        /* Implementation Specific (for */
                                        /* example RS-232 HCI defines   */
                                        /* two Additional HCI Packet    */
                                        /* Types which are numbered     */
                                        /* 0x05 and 0x06 for RS-232 HCI.*/
} HCI_PacketType_t;

typedef struct _tagHCI_Packet_t
{
   HCI_PacketType_t HCIPacketType;
   unsigned int     HCIPacketLength;
   unsigned char    HCIPacketData[1];
} HCI_Packet_t;

typedef struct _tagHCI_Packet_Header_t
{
   HCI_PacketType_t  HCIPacketType;
   unsigned int      HCIPacketLength;
   unsigned char    *HCIPacketData;
} HCI_Packet_Header_t;

typedef struct _Inquiry_Command_Typedef
{
	uint8_t 	Packet_type;
	uint8_t		Lap_High;
	uint16_t  Lap_Low;
	uint8_t   Inquiry_Length;
	uint8_t   Num_Responses;
	
}Inquiry_Command_Typedef;

#define HCI_PACKET_HEADER_HEADER_SIZE                    (sizeof(HCI_Packet_Header_t))

   /* HCI Command Declarations/Types/Constants.                         */

   /* The following MACRO is provided to allow the programmer a very    */
   /* simple means of making an HCI Command Packet OpCode.  The OpCode  */
   /* Generated can be directly assigned to the OpCode field, so that   */
   /* the programmer does NOT have to translate Big Endian/Little       */
   /* Endian.  The OpCode itself NEEDS to be stored in the OpCode field */
   /* in Little Endian Format.  The first parameter is the OGF and the  */
   /* second parameter of the MACRO is the OCF of the Command.          */
#define HCI_MAKE_COMMAND_OPCODE(_x, _y) (((((uint16_t)(_x)) << 10) & 0xFC00) | (((uint16_t)(_y)) & 0x03FF))

   /* HCI Command Code OGF Definitions.                                 */
#define HCI_COMMAND_CODE_NULL_OGF                                       0x00
#define HCI_COMMAND_CODE_LINK_CONTROL_OGF                               0x01
#define HCI_COMMAND_CODE_LINK_POLICY_OGF                                0x02
#define HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF                           0x03
#define HCI_COMMAND_CODE_INFORMATIONAL_PARAMETERS_OGF                   0x04
#define HCI_COMMAND_CODE_STATUS_PARAMETERS_OGF                          0x05
#define HCI_COMMAND_CODE_TESTING_COMMANDS_OGF                           0x06
#define HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF                     0x08

#define HCI_COMMAND_CODE_BLUETOOTH_LOGO_TESTING_OGF                     0x3E
#define HCI_COMMAND_CODE_VENDOR_SPECIFIC_DEBUG_OGF                      0x3F
   /* HCI Command Code OCF Definitions (Link Control).                  */
#define HCI_COMMAND_CODE_INQUIRY_OCF                                    0x0001
#define HCI_COMMAND_CODE_INQUIRY_CANCEL_OCF                             0x0002
#define HCI_COMMAND_CODE_PERIODIC_INQUIRY_MODE_OCF                      0x0003
#define HCI_COMMAND_CODE_EXIT_PERIODIC_INQUIRY_MODE_OCF                 0x0004
#define HCI_COMMAND_CODE_CREATE_CONNECTION_OCF                          0x0005
#define HCI_COMMAND_CODE_DISCONNECT_OCF                                 0x0006
#define HCI_COMMAND_CODE_ADD_SCO_CONNECTION_OCF                         0x0007
#define HCI_COMMAND_CODE_ACCEPT_CONNECTION_REQUEST_OCF                  0x0009
#define HCI_COMMAND_CODE_REJECT_CONNECTION_REQUEST_OCF                  0x000A
#define HCI_COMMAND_CODE_LINK_KEY_REQUEST_REPLY_OCF                     0x000B
#define HCI_COMMAND_CODE_LINK_KEY_REQUEST_NEGATIVE_REPLY_OCF            0x000C
#define HCI_COMMAND_CODE_PIN_CODE_REQUEST_REPLY_OCF                     0x000D
#define HCI_COMMAND_CODE_PIN_CODE_REQUEST_NEGATIVE_REPLY_OCF            0x000E
#define HCI_COMMAND_CODE_CHANGE_CONNECTION_PACKET_TYPE_OCF              0x000F
#define HCI_COMMAND_CODE_AUTHENTICATION_REQUESTED_OCF                   0x0011
#define HCI_COMMAND_CODE_SET_CONNECTION_ENCRYPTION_OCF                  0x0013
#define HCI_COMMAND_CODE_CHANGE_CONNECTION_LINK_KEY_OCF                 0x0015
#define HCI_COMMAND_CODE_MASTER_LINK_KEY_OCF                            0x0017
#define HCI_COMMAND_CODE_REMOTE_NAME_REQUEST_OCF                        0x0019
#define HCI_COMMAND_CODE_READ_REMOTE_SUPPORTED_FEATURES_OCF             0x001B
#define HCI_COMMAND_CODE_READ_REMOTE_VERSION_INFORMATION_OCF            0x001D
#define HCI_COMMAND_CODE_READ_CLOCK_OFFSET_OCF                          0x001F

   /* HCI Command Code OCF Definitions (Link Control - Version 1.2).    */
#define HCI_COMMAND_CODE_CREATE_CONNECTION_CANCEL_OCF                   0x0008
#define HCI_COMMAND_CODE_REMOTE_NAME_REQUEST_CANCEL_OCF                 0x001A
#define HCI_COMMAND_CODE_READ_REMOTE_EXTENDED_FEATURES_OCF              0x001C
#define HCI_COMMAND_CODE_READ_LMP_HANDLE_OCF                            0x0020
#define HCI_COMMAND_CODE_SETUP_SYNCHRONOUS_CONNECTION_OCF               0x0028
#define HCI_COMMAND_CODE_ACCEPT_SYNCHRONOUS_CONNECTION_OCF              0x0029
#define HCI_COMMAND_CODE_REJECT_SYNCHRONOUS_CONNECTION_OCF              0x002A

   /* HCI Command Code OCF Definitions (Link Control - Version 2.1 +    */
   /* EDR).                                                             */
#define HCI_COMMAND_CODE_IO_CAPABILITY_REQUEST_REPLY_OCF                0x002B
#define HCI_COMMAND_CODE_USER_CONFIRMATION_REQUEST_REPLY_OCF            0x002C
#define HCI_COMMAND_CODE_USER_CONFIRMATION_REQUEST_NEGATIVE_REPLY_OCF   0x002D
#define HCI_COMMAND_CODE_USER_PASSKEY_REQUEST_REPLY_OCF                 0x002E
#define HCI_COMMAND_CODE_USER_PASSKEY_REQUEST_NEGATIVE_REPLY_OCF        0x002F
#define HCI_COMMAND_CODE_REMOTE_OOB_DATA_REQUEST_REPLY_OCF              0x0030
#define HCI_COMMAND_CODE_REMOTE_OOB_DATA_REQUEST_NEGATIVE_REPLY_OCF     0x0033
#define HCI_COMMAND_CODE_IO_CAPABILITY_REQUEST_NEGATIVE_REPLY_OCF       0x0034

   /* HCI Command Code OCF Definitions (Link Control - Version 3.0 +    */
   /* HS).                                                              */
#define HCI_COMMAND_CODE_CREATE_PHYSICAL_LINK_OCF                       0x0035
#define HCI_COMMAND_CODE_ACCEPT_PHYSICAL_LINK_REQUEST_OCF               0x0036
#define HCI_COMMAND_CODE_DISCONNECT_PHYSICAL_LINK_OCF                   0x0037
#define HCI_COMMAND_CODE_CREATE_LOGICAL_LINK_OCF                        0x0038
#define HCI_COMMAND_CODE_ACCEPT_LOGICAL_LINK_OCF                        0x0039
#define HCI_COMMAND_CODE_DISCONNECT_LOGICAL_LINK_OCF                    0x003A
#define HCI_COMMAND_CODE_LOGICAL_LINK_CANCEL_OCF                        0x003B
#define HCI_COMMAND_CODE_FLOW_SPEC_MODIFY_OCF                           0x003C

   /* HCI Command Code OCF Definitions (Link Policy).                   */
#define HCI_COMMAND_CODE_HOLD_MODE_OCF                                  0x0001
#define HCI_COMMAND_CODE_SNIFF_MODE_OCF                                 0x0003
#define HCI_COMMAND_CODE_EXIT_SNIFF_MODE_OCF                            0x0004
#define HCI_COMMAND_CODE_PARK_MODE_OCF                                  0x0005
#define HCI_COMMAND_CODE_EXIT_PARK_MODE_OCF                             0x0006
#define HCI_COMMAND_CODE_QOS_SETUP_OCF                                  0x0007
#define HCI_COMMAND_CODE_ROLE_DISCOVERY_OCF                             0x0009
#define HCI_COMMAND_CODE_SWITCH_ROLE_OCF                                0x000B
#define HCI_COMMAND_CODE_READ_LINK_POLICY_SETTINGS_OCF                  0x000C
#define HCI_COMMAND_CODE_WRITE_LINK_POLICY_SETTINGS_OCF                 0x000D

   /* HCI Command Code OCF Definitions (Link Policy - Version 1.2).     */
#define HCI_COMMAND_CODE_READ_DEFAULT_LINK_POLICY_SETTINGS_OCF          0x000E
#define HCI_COMMAND_CODE_WRITE_DEFAULT_LINK_POLICY_SETTINGS_OCF         0x000F
#define HCI_COMMAND_CODE_FLOW_SPECIFICATION_OCF                         0x0010

   /* HCI Command Code OCF Definitions (Link Policy - Version 2.1 +     */
   /* EDR).                                                             */
#define HCI_COMMAND_CODE_SNIFF_SUBRATING_OCF                            0x0011

   /* HCI Command Code OCF Definitions (Host Control and Baseband).     */
#define HCI_COMMAND_CODE_SET_EVENT_MASK_OCF                             0x0001
#define HCI_COMMAND_CODE_RESET_OCF                                      0x0003
#define HCI_COMMAND_CODE_SET_EVENT_FILTER_OCF                           0x0005
#define HCI_COMMAND_CODE_FLUSH_OCF                                      0x0008
#define HCI_COMMAND_CODE_READ_PIN_TYPE_OCF                              0x0009
#define HCI_COMMAND_CODE_WRITE_PIN_TYPE_OCF                             0x000A
#define HCI_COMMAND_CODE_CREATE_NEW_UNIT_KEY_OCF                        0x000B
#define HCI_COMMAND_CODE_READ_STORED_LINK_KEY_OCF                       0x000D
#define HCI_COMMAND_CODE_WRITE_STORED_LINK_KEY_OCF                      0x0011
#define HCI_COMMAND_CODE_DELETE_STORED_LINK_KEY_OCF                     0x0012
#define HCI_COMMAND_CODE_CHANGE_LOCAL_NAME_OCF                          0x0013
#define HCI_COMMAND_CODE_WRITE_LOCAL_NAME_OCF                           0x0013
#define HCI_COMMAND_CODE_READ_LOCAL_NAME_OCF                            0x0014
#define HCI_COMMAND_CODE_READ_CONNECTION_ACCEPT_TIMEOUT_OCF             0x0015
#define HCI_COMMAND_CODE_WRITE_CONNECTION_ACCEPT_TIMEOUT_OCF            0x0016
#define HCI_COMMAND_CODE_READ_PAGE_TIMEOUT_OCF                          0x0017
#define HCI_COMMAND_CODE_WRITE_PAGE_TIMEOUT_OCF                         0x0018
#define HCI_COMMAND_CODE_READ_SCAN_ENABLE_OCF                           0x0019
#define HCI_COMMAND_CODE_WRITE_SCAN_ENABLE_OCF                          0x001A
#define HCI_COMMAND_CODE_READ_PAGE_SCAN_ACTIVITY_OCF                    0x001B
#define HCI_COMMAND_CODE_WRITE_PAGE_SCAN_ACTIVITY_OCF                   0x001C
#define HCI_COMMAND_CODE_READ_INQUIRY_SCAN_ACTIVITY_OCF                 0x001D
#define HCI_COMMAND_CODE_WRITE_INQUIRY_SCAN_ACTIVITY_OCF                0x001E
#define HCI_COMMAND_CODE_READ_AUTHENTICATION_ENABLE_OCF                 0x001F
#define HCI_COMMAND_CODE_WRITE_AUTHENTICATION_ENABLE_OCF                0x0020
#define HCI_COMMAND_CODE_READ_ENCRYPTION_MODE_OCF                       0x0021
#define HCI_COMMAND_CODE_WRITE_ENCRYPTION_MODE_OCF                      0x0022
#define HCI_COMMAND_CODE_READ_CLASS_OF_DEVICE_OCF                       0x0023
#define HCI_COMMAND_CODE_WRITE_CLASS_OF_DEVICE_OCF                      0x0024
#define HCI_COMMAND_CODE_READ_VOICE_SETTING_OCF                         0x0025
#define HCI_COMMAND_CODE_WRITE_VOICE_SETTING_OCF                        0x0026
#define HCI_COMMAND_CODE_READ_AUTOMATIC_FLUSH_TIMEOUT_OCF               0x0027
#define HCI_COMMAND_CODE_WRITE_AUTOMATIC_FLUSH_TIMEOUT_OCF              0x0028
#define HCI_COMMAND_CODE_READ_NUM_BROADCAST_RETRANSMISSIONS_OCF         0x0029
#define HCI_COMMAND_CODE_WRITE_NUM_BROADCAST_RETRANSMISSIONS_OCF        0x002A
#define HCI_COMMAND_CODE_READ_HOLD_MODE_ACTIVITY_OCF                    0x002B
#define HCI_COMMAND_CODE_WRITE_HOLD_MODE_ACTIVITY_OCF                   0x002C
#define HCI_COMMAND_CODE_READ_TRANSMIT_POWER_LEVEL_OCF                  0x002D
#define HCI_COMMAND_CODE_READ_SCO_FLOW_CONTROL_ENABLE_OCF               0x002E
#define HCI_COMMAND_CODE_READ_SYNCHRONOUS_FLOW_CONTROL_ENABLE_OCF       0x002E
#define HCI_COMMAND_CODE_WRITE_SCO_FLOW_CONTROL_ENABLE_OCF              0x002F
#define HCI_COMMAND_CODE_WRITE_SYNCHRONOUS_FLOW_CONTROL_ENABLE_OCF      0x002F
#define HCI_COMMAND_CODE_SET_HOST_CONTROLLER_TO_HOST_FLOW_CONTROL_OCF   0x0031
#define HCI_COMMAND_CODE_HOST_BUFFER_SIZE_OCF                           0x0033
#define HCI_COMMAND_CODE_HOST_NUMBER_OF_COMPLETED_PACKETS_OCF           0x0035
#define HCI_COMMAND_CODE_READ_LINK_SUPERVISION_TIMEOUT_OCF              0x0036
#define HCI_COMMAND_CODE_WRITE_LINK_SUPERVISION_TIMEOUT_OCF             0x0037
#define HCI_COMMAND_CODE_READ_NUMBER_OF_SUPPORTED_IAC_OCF               0x0038
#define HCI_COMMAND_CODE_READ_CURRENT_IAC_LAP_OCF                       0x0039
#define HCI_COMMAND_CODE_WRITE_CURRENT_IAC_LAP_OCF                      0x003A
#define HCI_COMMAND_CODE_READ_PAGE_SCAN_PERIOD_MODE_OCF                 0x003B
#define HCI_COMMAND_CODE_WRITE_PAGE_SCAN_PERIOD_MODE_OCF                0x003C
#define HCI_COMMAND_CODE_READ_PAGE_SCAN_MODE_OCF                        0x003D
#define HCI_COMMAND_CODE_WRITE_PAGE_SCAN_MODE_OCF                       0x003E

   /* HCI Command Code OCF Definitions (Host Control and Baseband -     */
   /* Version 1.2).                                                     */
#define HCI_COMMAND_CODE_SET_AFH_HOST_CHANNEL_CLASSIFICATION_OCF        0x003F
#define HCI_COMMAND_CODE_READ_INQUIRY_SCAN_TYPE_OCF                     0x0042
#define HCI_COMMAND_CODE_WRITE_INQUIRY_SCAN_TYPE_OCF                    0x0043
#define HCI_COMMAND_CODE_READ_INQUIRY_MODE_OCF                          0x0044
#define HCI_COMMAND_CODE_WRITE_INQUIRY_MODE_OCF                         0x0045
#define HCI_COMMAND_CODE_READ_PAGE_SCAN_TYPE_OCF                        0x0046
#define HCI_COMMAND_CODE_WRITE_PAGE_SCAN_TYPE_OCF                       0x0047
#define HCI_COMMAND_CODE_READ_AFH_CHANNEL_ASSESSMENT_MODE_OCF           0x0048
#define HCI_COMMAND_CODE_WRITE_AFH_CHANNEL_ASSESSMENT_MODE_OCF          0x0049

   /* HCI Command Code OCF Definitions (Host Control and Baseband -     */
   /* Version 2.1 + EDR).                                               */
#define HCI_COMMAND_CODE_READ_EXTENDED_INQUIRY_RESPONSE_OCF             0x0051
#define HCI_COMMAND_CODE_WRITE_EXTENDED_INQUIRY_RESPONSE_OCF            0x0052
#define HCI_COMMAND_CODE_REFRESH_ENCRYPTION_KEY_OCF                     0x0053
#define HCI_COMMAND_CODE_READ_SIMPLE_PAIRING_MODE_OCF                   0x0055
#define HCI_COMMAND_CODE_WRITE_SIMPLE_PAIRING_MODE_OCF                  0x0056
#define HCI_COMMAND_CODE_READ_LOCAL_OOB_DATA_OCF                        0x0057
#define HCI_COMMAND_CODE_READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL_OCF 0x0058
#define HCI_COMMAND_CODE_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL_OCF         0x0059
#define HCI_COMMAND_CODE_READ_DEFAULT_ERRONEOUS_DATA_REPORTING_OCF      0x005A
#define HCI_COMMAND_CODE_WRITE_DEFAULT_ERRONEOUS_DATA_REPORTING_OCF     0x005B
#define HCI_COMMAND_CODE_ENHANCED_FLUSH_OCF                             0x005F
#define HCI_COMMAND_CODE_SEND_KEYPRESS_NOTIFICATION_OCF                 0x0060

   /* HCI Command Code OCF Definitions (Host Control and Baseband -     */
   /* Version 3.0 + HS).                                                */
#define HCI_COMMAND_CODE_READ_LOGICAL_LINK_ACCEPT_TIMEOUT_OCF           0x0061
#define HCI_COMMAND_CODE_WRITE_LOGICAL_LINK_ACCEPT_TIMEOUT_OCF          0x0062
#define HCI_COMMAND_CODE_SET_EVENT_MASK_PAGE_2_OCF                      0x0063
#define HCI_COMMAND_CODE_READ_LOCATION_DATA_OCF                         0x0064
#define HCI_COMMAND_CODE_WRITE_LOCATION_DATA_OCF                        0x0065
#define HCI_COMMAND_CODE_READ_FLOW_CONTROL_MODE_OCF                     0x0066
#define HCI_COMMAND_CODE_WRITE_FLOW_CONTROL_MODE_OCF                    0x0067
#define HCI_COMMAND_CODE_READ_ENHANCED_TRANSMIT_POWER_LEVEL_OCF         0x0068
#define HCI_COMMAND_CODE_READ_BEST_EFFORT_FLUSH_TIMEOUT_OCF             0x0069
#define HCI_COMMAND_CODE_WRITE_BEST_EFFORT_FLUSH_TIMEOUT_OCF            0x006A
#define HCI_COMMAND_CODE_SHORT_RANGE_MODE_OCF                           0x006B

   /* HCI Command Code OCF Definitions (Host Control and Baseband -     */
   /* Version 4.0 + LE).                                                */
#define HCI_COMMAND_CODE_READ_LE_HOST_SUPPORTED_OCF                     0x006C
#define HCI_COMMAND_CODE_WRITE_LE_HOST_SUPPORTED_OCF                    0x006D
#define HCI_COMMAND_CODE_SET_MWS_TRANSPORT_LAYER_OCF										0x0071

   /* HCI Command Code OCF Definitions (Informational Parameters).      */
#define HCI_COMMAND_CODE_READ_LOCAL_VERSION_INFORMATION_OCF             0x0001
#define HCI_COMMAND_CODE_READ_LOCAL_SUPPORTED_FEATURES_OCF              0x0003
#define HCI_COMMAND_CODE_READ_BUFFER_SIZE_OCF                           0x0005
#define HCI_COMMAND_CODE_READ_COUNTRY_CODE_OCF                          0x0007
#define HCI_COMMAND_CODE_READ_BD_ADDR_OCF                               0x0009

   /* HCI Command Code OCF Definitions (Informational Parameters -      */
   /* Version 1.2)                                                      */
#define HCI_COMMAND_CODE_READ_LOCAL_SUPPORTED_COMMANDS_OCF              0x0002
#define HCI_COMMAND_CODE_READ_LOCAL_EXTENDED_FEATURES_OCF               0x0004

   /* HCI Command Code OCF Definitions (Informational Parameters -      */
   /* Version 3.0 + HS).                                                */
#define HCI_COMMAND_CODE_READ_DATA_BLOCK_SIZE_OCF                       0x000A

   /* HCI Command Code OCF Definitions (Status Parameters).             */
#define HCI_COMMAND_CODE_READ_FAILED_CONTACT_COUNTER_OCF                0x0001
#define HCI_COMMAND_CODE_RESET_FAILED_CONTACT_COUNTER_OCF               0x0002
#define HCI_COMMAND_CODE_GET_LINK_QUALITY_OCF                           0x0003
#define HCI_COMMAND_CODE_READ_RSSI_OCF                                  0x0005

   /* HCI Command Code OCF Definitions (Status Parameters - Version     */
   /* 1.2).                                                             */
#define HCI_COMMAND_CODE_READ_AFH_CHANNEL_MAP_OCF                       0x0006
#define HCI_COMMAND_CODE_READ_CLOCK_OCF                                 0x0007

   /* HCI Command Code OCF Definitions (Status Parameters - Version 3.0 */
   /* + HS).                                                            */
#define HCI_COMMAND_CODE_READ_ENCRYPTION_KEY_SIZE_OCF                   0x0008
#define HCI_COMMAND_CODE_READ_LOCAL_AMP_INFO_OCF                        0x0009
#define HCI_COMMAND_CODE_READ_LOCAL_AMP_ASSOC_OCF                       0x000A
#define HCI_COMMAND_CODE_WRITE_REMOTE_AMP_ASSOC_OCF                     0x000B

   /* HCI Command Code OCF Definitions (Testing Commands).              */
#define HCI_COMMAND_CODE_READ_LOOPBACK_MODE_OCF                         0x0001
#define HCI_COMMAND_CODE_WRITE_LOOPBACK_MODE_OCF                        0x0002
#define HCI_COMMAND_CODE_ENABLE_DEVICE_UNDER_TEST_MODE_OCF              0x0003

   /* HCI Command Code OCF Definitions (Testing Commands - Version 2.1 +*/
   /* EDR).                                                             */
#define HCI_COMMAND_CODE_WRITE_SIMPLE_PAIRING_DEBUG_MODE_OCF            0x0004

   /* HCI Command Code OCF Definitions (Testing Commands - Version 3.0 +*/
   /* HS).                                                              */
#define HCI_COMMAND_CODE_ENABLE_AMP_RECEIVER_REPORTS_OCF                0x0007
#define HCI_COMMAND_CODE_AMP_TEST_END_OCF                               0x0008
#define HCI_COMMAND_CODE_AMP_TEST_OCF                                   0x0009

   /* HCI Command Code OCF Definitions (LE Commands - Version 4.0 + LE).*/
#define HCI_COMMAND_CODE_LE_SET_EVENT_MASK_OCF                          0x0001
#define HCI_COMMAND_CODE_LE_READ_BUFFER_SIZE_OCF                        0x0002
#define HCI_COMMAND_CODE_LE_READ_LOCAL_SUPPORTED_FEATURES_OCF           0x0003
#define HCI_COMMAND_CODE_LE_SET_RANDOM_ADDRESS_OCF                      0x0005
#define HCI_COMMAND_CODE_LE_SET_ADVERTISING_PARAMETERS_OCF              0x0006
#define HCI_COMMAND_CODE_LE_READ_ADVERTISING_CHANNEL_TX_POWER_OCF       0x0007
#define HCI_COMMAND_CODE_LE_SET_ADVERTISING_DATA_OCF                    0x0008
#define HCI_COMMAND_CODE_LE_SET_SCAN_RESPONSE_DATA_OCF                  0x0009
#define HCI_COMMAND_CODE_LE_SET_ADVERTISE_ENABLE_OCF                    0x000A
#define HCI_COMMAND_CODE_LE_SET_SCAN_PARAMETERS_OCF                     0x000B
#define HCI_COMMAND_CODE_LE_SET_SCAN_ENABLE_OCF                         0x000C
#define HCI_COMMAND_CODE_LE_CREATE_CONNECTION_OCF                       0x000D
#define HCI_COMMAND_CODE_LE_CREATE_CONNECTION_CANCEL_OCF                0x000E
#define HCI_COMMAND_CODE_LE_READ_WHITE_LIST_SIZE_OCF                    0x000F
#define HCI_COMMAND_CODE_LE_CLEAR_WHITE_LIST_OCF                        0x0010
#define HCI_COMMAND_CODE_LE_ADD_DEVICE_TO_WHITE_LIST_OCF                0x0011
#define HCI_COMMAND_CODE_LE_REMOVE_DEVICE_FROM_WHITE_LIST_OCF           0x0012
#define HCI_COMMAND_CODE_LE_CONNECTION_UPDATE_OCF                       0x0013
#define HCI_COMMAND_CODE_LE_SET_HOST_CHANNEL_CLASSIFICATION_OCF         0x0014
#define HCI_COMMAND_CODE_LE_READ_CHANNEL_MAP_OCF                        0x0015
#define HCI_COMMAND_CODE_LE_READ_REMOTE_USED_FEATURES_OCF               0x0016
#define HCI_COMMAND_CODE_LE_ENCRYPT_OCF                                 0x0017
#define HCI_COMMAND_CODE_LE_RAND_OCF                                    0x0018
#define HCI_COMMAND_CODE_LE_START_ENCRYPTION_OCF                        0x0019
#define HCI_COMMAND_CODE_LE_LONG_TERM_KEY_REQUEST_REPLY_OCF             0x001A
#define HCI_COMMAND_CODE_LE_LONG_TERM_KEY_REQUEST_NEGATIVE_REPLY_OCF    0x001B
#define HCI_COMMAND_CODE_LE_READ_SUPPORTED_STATES_OCF                   0x001C
#define HCI_COMMAND_CODE_LE_RECEIVER_TEST_OCF                           0x001D
#define HCI_COMMAND_CODE_LE_TRANSMITTER_TEST_OCF                        0x001E
#define HCI_COMMAND_CODE_LE_TEST_END_OCF                                0x001F


   /* HCI Command Code OpCode Definitions (NULL OpCode).                */
#define HCI_COMMAND_OPCODE_NULL                                         (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_NULL_OGF, HCI_COMMAND_CODE_NULL_OCF))

   /* HCI Command Code OpCode Definitions (Link Control).               */
#define HCI_COMMAND_OPCODE_INQUIRY                                      (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_INQUIRY_OCF))
#define HCI_COMMAND_OPCODE_INQUIRY_CANCEL                               (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_INQUIRY_CANCEL_OCF))
#define HCI_COMMAND_OPCODE_PERIODIC_INQUIRY_MODE                        (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_PERIODIC_INQUIRY_MODE_OCF))
#define HCI_COMMAND_OPCODE_EXIT_PERIODIC_INQUIRY_MODE                   (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_EXIT_PERIODIC_INQUIRY_MODE_OCF))
#define HCI_COMMAND_OPCODE_CREATE_CONNECTION                            (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_CREATE_CONNECTION_OCF))
#define HCI_COMMAND_OPCODE_DISCONNECT                                   (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_DISCONNECT_OCF))
#define HCI_COMMAND_OPCODE_ADD_SCO_CONNECTION                           (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_ADD_SCO_CONNECTION_OCF))
#define HCI_COMMAND_OPCODE_ACCEPT_CONNECTION_REQUEST                    (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_ACCEPT_CONNECTION_REQUEST_OCF))
#define HCI_COMMAND_OPCODE_REJECT_CONNECTION_REQUEST                    (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_REJECT_CONNECTION_REQUEST_OCF))
#define HCI_COMMAND_OPCODE_LINK_KEY_REQUEST_REPLY                       (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_LINK_KEY_REQUEST_REPLY_OCF))
#define HCI_COMMAND_OPCODE_LINK_KEY_REQUEST_NEGATIVE_REPLY              (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_LINK_KEY_REQUEST_NEGATIVE_REPLY_OCF))
#define HCI_COMMAND_OPCODE_PIN_CODE_REQUEST_REPLY                       (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_PIN_CODE_REQUEST_REPLY_OCF))
#define HCI_COMMAND_OPCODE_PIN_CODE_REQUEST_NEGATIVE_REPLY              (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_PIN_CODE_REQUEST_NEGATIVE_REPLY_OCF))
#define HCI_COMMAND_OPCODE_CHANGE_CONNECTION_PACKET_TYPE                (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_CHANGE_CONNECTION_PACKET_TYPE_OCF))
#define HCI_COMMAND_OPCODE_AUTHENTICATION_REQUESTED                     (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_AUTHENTICATION_REQUESTED_OCF))
#define HCI_COMMAND_OPCODE_SET_CONNECTION_ENCRYPTION                    (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_SET_CONNECTION_ENCRYPTION_OCF))
#define HCI_COMMAND_OPCODE_CHANGE_CONNECTION_LINK_KEY                   (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_CHANGE_CONNECTION_LINK_KEY_OCF))
#define HCI_COMMAND_OPCODE_MASTER_LINK_KEY                              (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_MASTER_LINK_KEY_OCF))
#define HCI_COMMAND_OPCODE_REMOTE_NAME_REQUEST                          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_REMOTE_NAME_REQUEST_OCF))
#define HCI_COMMAND_OPCODE_READ_REMOTE_SUPPORTED_FEATURES               (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_READ_REMOTE_SUPPORTED_FEATURES_OCF))
#define HCI_COMMAND_OPCODE_READ_REMOTE_VERSION_INFORMATION              (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_READ_REMOTE_VERSION_INFORMATION_OCF))
#define HCI_COMMAND_OPCODE_READ_CLOCK_OFFSET                            (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_READ_CLOCK_OFFSET_OCF))

   /* HCI Command Code OpCode Definitions (Link Control - Version 1.2). */
#define HCI_COMMAND_OPCODE_CREATE_CONNECTION_CANCEL                     (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_CREATE_CONNECTION_CANCEL_OCF))
#define HCI_COMMAND_OPCODE_REMOTE_NAME_REQUEST_CANCEL                   (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_REMOTE_NAME_REQUEST_CANCEL_OCF))
#define HCI_COMMAND_OPCODE_READ_REMOTE_EXTENDED_FEATURES                (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_READ_REMOTE_EXTENDED_FEATURES_OCF))
#define HCI_COMMAND_OPCODE_READ_LMP_HANDLE                              (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_READ_LMP_HANDLE_OCF))
#define HCI_COMMAND_OPCODE_SETUP_SYNCHRONOUS_CONNECTION                 (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_SETUP_SYNCHRONOUS_CONNECTION_OCF))
#define HCI_COMMAND_OPCODE_ACCEPT_SYNCHRONOUS_CONNECTION                (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_ACCEPT_SYNCHRONOUS_CONNECTION_OCF))
#define HCI_COMMAND_OPCODE_REJECT_SYNCHRONOUS_CONNECTION                (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_REJECT_SYNCHRONOUS_CONNECTION_OCF))

   /* HCI Command Code OpCode Definitions (Link Control - Version 2.1 + */
   /* EDR).                                                             */
#define HCI_COMMAND_OPCODE_IO_CAPABILITY_REQUEST_REPLY                  (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_IO_CAPABILITY_REQUEST_REPLY_OCF))
#define HCI_COMMAND_OPCODE_USER_CONFIRMATION_REQUEST_REPLY              (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_USER_CONFIRMATION_REQUEST_REPLY_OCF))
#define HCI_COMMAND_OPCODE_USER_CONFIRMATION_REQUEST_NEGATIVE_REPLY     (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_USER_CONFIRMATION_REQUEST_NEGATIVE_REPLY_OCF))
#define HCI_COMMAND_OPCODE_USER_PASSKEY_REQUEST_REPLY                   (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_USER_PASSKEY_REQUEST_REPLY_OCF))
#define HCI_COMMAND_OPCODE_USER_PASSKEY_REQUEST_NEGATIVE_REPLY          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_USER_PASSKEY_REQUEST_NEGATIVE_REPLY_OCF))
#define HCI_COMMAND_OPCODE_REMOTE_OOB_DATA_REQUEST_REPLY                (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_REMOTE_OOB_DATA_REQUEST_REPLY_OCF))
#define HCI_COMMAND_OPCODE_REMOTE_OOB_DATA_REQUEST_NEGATIVE_REPLY       (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_REMOTE_OOB_DATA_REQUEST_NEGATIVE_REPLY_OCF))
#define HCI_COMMAND_OPCODE_IO_CAPABILITY_REQUEST_NEGATIVE_REPLY         (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_IO_CAPABILITY_REQUEST_NEGATIVE_REPLY_OCF))

   /* HCI Command Code OpCode Definitions (Link Control - Version 3.0 + */
   /* HS).                                                              */
#define HCI_COMMAND_OPCODE_CREATE_PHYSICAL_LINK                         (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_CREATE_PHYSICAL_LINK_OCF))
#define HCI_COMMAND_OPCODE_ACCEPT_PHYSICAL_LINK_REQUEST                 (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_ACCEPT_PHYSICAL_LINK_REQUEST_OCF))
#define HCI_COMMAND_OPCODE_DISCONNECT_PHYSICAL_LINK                     (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_DISCONNECT_PHYSICAL_LINK_OCF))
#define HCI_COMMAND_OPCODE_CREATE_LOGICAL_LINK                          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_CREATE_LOGICAL_LINK_OCF))
#define HCI_COMMAND_OPCODE_ACCEPT_LOGICAL_LINK                          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_ACCEPT_LOGICAL_LINK_OCF))
#define HCI_COMMAND_OPCODE_DISCONNECT_LOGICAL_LINK                      (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_DISCONNECT_LOGICAL_LINK_OCF))
#define HCI_COMMAND_OPCODE_LOGICAL_LINK_CANCEL                          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_LOGICAL_LINK_CANCEL_OCF))
#define HCI_COMMAND_OPCODE_FLOW_SPEC_MODIFY                             (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_CONTROL_OGF, HCI_COMMAND_CODE_FLOW_SPEC_MODIFY_OCF))

   /* HCI Command Code OpCode Definitions (Link Policy).                */
#define HCI_COMMAND_OPCODE_HOLD_MODE                                    (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_POLICY_OGF, HCI_COMMAND_CODE_HOLD_MODE_OCF))
#define HCI_COMMAND_OPCODE_SNIFF_MODE                                   (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_POLICY_OGF, HCI_COMMAND_CODE_SNIFF_MODE_OCF))
#define HCI_COMMAND_OPCODE_EXIT_SNIFF_MODE                              (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_POLICY_OGF, HCI_COMMAND_CODE_EXIT_SNIFF_MODE_OCF))
#define HCI_COMMAND_OPCODE_PARK_MODE                                    (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_POLICY_OGF, HCI_COMMAND_CODE_PARK_MODE_OCF))
#define HCI_COMMAND_OPCODE_EXIT_PARK_MODE                               (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_POLICY_OGF, HCI_COMMAND_CODE_EXIT_PARK_MODE_OCF))
#define HCI_COMMAND_OPCODE_QOS_SETUP                                    (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_POLICY_OGF, HCI_COMMAND_CODE_QOS_SETUP_OCF))
#define HCI_COMMAND_OPCODE_ROLE_DISCOVERY                               (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_POLICY_OGF, HCI_COMMAND_CODE_ROLE_DISCOVERY_OCF))
#define HCI_COMMAND_OPCODE_SWITCH_ROLE                                  (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_POLICY_OGF, HCI_COMMAND_CODE_SWITCH_ROLE_OCF))
#define HCI_COMMAND_OPCODE_READ_LINK_POLICY_SETTINGS                    (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_POLICY_OGF, HCI_COMMAND_CODE_READ_LINK_POLICY_SETTINGS_OCF))
#define HCI_COMMAND_OPCODE_WRITE_LINK_POLICY_SETTINGS                   (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_POLICY_OGF, HCI_COMMAND_CODE_WRITE_LINK_POLICY_SETTINGS_OCF))

   /* HCI Command Code OpCode Definitions (Link Policy - Version 1.2).  */
#define HCI_COMMAND_OPCODE_READ_DEFAULT_LINK_POLICY_SETTINGS            (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_POLICY_OGF, HCI_COMMAND_CODE_READ_DEFAULT_LINK_POLICY_SETTINGS_OCF))
#define HCI_COMMAND_OPCODE_WRITE_DEFAULT_LINK_POLICY_SETTINGS           (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_POLICY_OGF, HCI_COMMAND_CODE_WRITE_DEFAULT_LINK_POLICY_SETTINGS_OCF))
#define HCI_COMMAND_OPCODE_FLOW_SPECIFICATION                           (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_POLICY_OGF, HCI_COMMAND_CODE_FLOW_SPECIFICATION_OCF))

   /* HCI Command Code OpCode Definitions (Link Policy - Version 2.1 +  */
   /* EDR).                                                             */
#define HCI_COMMAND_OPCODE_SNIFF_SUBRATING                              (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LINK_POLICY_OGF, HCI_COMMAND_CODE_SNIFF_SUBRATING_OCF))

   /* HCI Command Code OpCode Definitions (Host Control and Baseband).  */
#define HCI_COMMAND_OPCODE_SET_EVENT_MASK                               (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_SET_EVENT_MASK_OCF))
#define HCI_COMMAND_OPCODE_RESET                                        (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_RESET_OCF))
#define HCI_COMMAND_OPCODE_SET_EVENT_FILTER                             (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_SET_EVENT_FILTER_OCF))
#define HCI_COMMAND_OPCODE_FLUSH                                        (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_FLUSH_OCF))
#define HCI_COMMAND_OPCODE_READ_PIN_TYPE                                (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_PIN_TYPE_OCF))
#define HCI_COMMAND_OPCODE_WRITE_PIN_TYPE                               (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_PIN_TYPE_OCF))
#define HCI_COMMAND_OPCODE_CREATE_NEW_UNIT_KEY                          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_CREATE_NEW_UNIT_KEY_OCF))
#define HCI_COMMAND_OPCODE_READ_STORED_LINK_KEY                         (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_STORED_LINK_KEY_OCF))
#define HCI_COMMAND_OPCODE_WRITE_STORED_LINK_KEY                        (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_STORED_LINK_KEY_OCF))
#define HCI_COMMAND_OPCODE_DELETE_STORED_LINK_KEY                       (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_DELETE_STORED_LINK_KEY_OCF))
#define HCI_COMMAND_OPCODE_CHANGE_LOCAL_NAME                            (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_CHANGE_LOCAL_NAME_OCF))
#define HCI_COMMAND_OPCODE_WRITE_LOCAL_NAME                             (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_LOCAL_NAME_OCF))
#define HCI_COMMAND_OPCODE_READ_LOCAL_NAME                              (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_LOCAL_NAME_OCF))
#define HCI_COMMAND_OPCODE_READ_CONNECTION_ACCEPT_TIMEOUT               (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_CONNECTION_ACCEPT_TIMEOUT_OCF))
#define HCI_COMMAND_OPCODE_WRITE_CONNECTION_ACCEPT_TIMEOUT              (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_CONNECTION_ACCEPT_TIMEOUT_OCF))
#define HCI_COMMAND_OPCODE_READ_PAGE_TIMEOUT                            (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_PAGE_TIMEOUT_OCF))
#define HCI_COMMAND_OPCODE_WRITE_PAGE_TIMEOUT                           (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_PAGE_TIMEOUT_OCF))
#define HCI_COMMAND_OPCODE_READ_SCAN_ENABLE                             (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_SCAN_ENABLE_OCF))
#define HCI_COMMAND_OPCODE_WRITE_SCAN_ENABLE                            (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_SCAN_ENABLE_OCF))
#define HCI_COMMAND_OPCODE_READ_PAGE_SCAN_ACTIVITY                      (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_PAGE_SCAN_ACTIVITY_OCF))
#define HCI_COMMAND_OPCODE_WRITE_PAGE_SCAN_ACTIVITY                     (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_PAGE_SCAN_ACTIVITY_OCF))
#define HCI_COMMAND_OPCODE_READ_INQUIRY_SCAN_ACTIVITY                   (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_INQUIRY_SCAN_ACTIVITY_OCF))
#define HCI_COMMAND_OPCODE_WRITE_INQUIRY_SCAN_ACTIVITY                  (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_INQUIRY_SCAN_ACTIVITY_OCF))
#define HCI_COMMAND_OPCODE_READ_AUTHENTICATION_ENABLE                   (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_AUTHENTICATION_ENABLE_OCF))
#define HCI_COMMAND_OPCODE_WRITE_AUTHENTICATION_ENABLE                  (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_AUTHENTICATION_ENABLE_OCF))
#define HCI_COMMAND_OPCODE_READ_ENCRYPTION_MODE                         (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_ENCRYPTION_MODE_OCF))
#define HCI_COMMAND_OPCODE_WRITE_ENCRYPTION_MODE                        (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_ENCRYPTION_MODE_OCF))
#define HCI_COMMAND_OPCODE_READ_CLASS_OF_DEVICE                         (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_CLASS_OF_DEVICE_OCF))
#define HCI_COMMAND_OPCODE_WRITE_CLASS_OF_DEVICE                        (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_CLASS_OF_DEVICE_OCF))
#define HCI_COMMAND_OPCODE_READ_VOICE_SETTING                           (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_VOICE_SETTING_OCF))
#define HCI_COMMAND_OPCODE_WRITE_VOICE_SETTING                          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_VOICE_SETTING_OCF))
#define HCI_COMMAND_OPCODE_READ_AUTOMATIC_FLUSH_TIMEOUT                 (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_AUTOMATIC_FLUSH_TIMEOUT_OCF))
#define HCI_COMMAND_OPCODE_WRITE_AUTOMATIC_FLUSH_TIMEOUT                (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_AUTOMATIC_FLUSH_TIMEOUT_OCF))
#define HCI_COMMAND_OPCODE_READ_NUM_BROADCAST_RETRANSMISSIONS           (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_NUM_BROADCAST_RETRANSMISSIONS_OCF))
#define HCI_COMMAND_OPCODE_WRITE_NUM_BROADCAST_RETRANSMISSIONS          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_NUM_BROADCAST_RETRANSMISSIONS_OCF))
#define HCI_COMMAND_OPCODE_READ_HOLD_MODE_ACTIVITY                      (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_HOLD_MODE_ACTIVITY_OCF))
#define HCI_COMMAND_OPCODE_WRITE_HOLD_MODE_ACTIVITY                     (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_HOLD_MODE_ACTIVITY_OCF))
#define HCI_COMMAND_OPCODE_READ_TRANSMIT_POWER_LEVEL                    (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_TRANSMIT_POWER_LEVEL_OCF))
#define HCI_COMMAND_OPCODE_READ_SCO_FLOW_CONTROL_ENABLE                 (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_SCO_FLOW_CONTROL_ENABLE_OCF))
#define HCI_COMMAND_OPCODE_READ_SYNCHRONOUS_FLOW_CONTROL_ENABLE         (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_SYNCHRONOUS_FLOW_CONTROL_ENABLE_OCF))
#define HCI_COMMAND_OPCODE_WRITE_SCO_FLOW_CONTROL_ENABLE                (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_SCO_FLOW_CONTROL_ENABLE_OCF))
#define HCI_COMMAND_OPCODE_WRITE_SYNCHRONOUS_FLOW_CONTROL_ENABLE        (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_SYNCHRONOUS_FLOW_CONTROL_ENABLE_OCF))
#define HCI_COMMAND_OPCODE_SET_HOST_CONTROLLER_TO_HOST_FLOW_CONTROL     (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_SET_HOST_CONTROLLER_TO_HOST_FLOW_CONTROL_OCF))
#define HCI_COMMAND_OPCODE_HOST_BUFFER_SIZE                             (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_HOST_BUFFER_SIZE_OCF))
#define HCI_COMMAND_OPCODE_HOST_NUMBER_OF_COMPLETED_PACKETS             (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_HOST_NUMBER_OF_COMPLETED_PACKETS_OCF))
#define HCI_COMMAND_OPCODE_READ_LINK_SUPERVISION_TIMEOUT                (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_LINK_SUPERVISION_TIMEOUT_OCF))
#define HCI_COMMAND_OPCODE_WRITE_LINK_SUPERVISION_TIMEOUT               (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_LINK_SUPERVISION_TIMEOUT_OCF))
#define HCI_COMMAND_OPCODE_READ_NUMBER_OF_SUPPORTED_IAC                 (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_NUMBER_OF_SUPPORTED_IAC_OCF))
#define HCI_COMMAND_OPCODE_READ_CURRENT_IAC_LAP                         (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_CURRENT_IAC_LAP_OCF))
#define HCI_COMMAND_OPCODE_WRITE_CURRENT_IAC_LAP                        (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_CURRENT_IAC_LAP_OCF))
#define HCI_COMMAND_OPCODE_READ_PAGE_SCAN_PERIOD_MODE                   (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_PAGE_SCAN_PERIOD_MODE_OCF))
#define HCI_COMMAND_OPCODE_WRITE_PAGE_SCAN_PERIOD_MODE                  (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_PAGE_SCAN_PERIOD_MODE_OCF))
#define HCI_COMMAND_OPCODE_READ_PAGE_SCAN_MODE                          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_PAGE_SCAN_MODE_OCF))
#define HCI_COMMAND_OPCODE_WRITE_PAGE_SCAN_MODE                         (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_PAGE_SCAN_MODE_OCF))

   /* HCI Command Code OpCode Definitions (Host Control and Baseband -  */
   /* Version 1.2).                                                     */
#define HCI_COMMAND_OPCODE_SET_AFH_HOST_CHANNEL_CLASSIFICATION          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_SET_AFH_HOST_CHANNEL_CLASSIFICATION_OCF))
#define HCI_COMMAND_OPCODE_READ_INQUIRY_SCAN_TYPE                       (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_INQUIRY_SCAN_TYPE_OCF))
#define HCI_COMMAND_OPCODE_WRITE_INQUIRY_SCAN_TYPE                      (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_INQUIRY_SCAN_TYPE_OCF))
#define HCI_COMMAND_OPCODE_READ_INQUIRY_MODE                            (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_INQUIRY_MODE_OCF))
#define HCI_COMMAND_OPCODE_WRITE_INQUIRY_MODE                           (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_INQUIRY_MODE_OCF))
#define HCI_COMMAND_OPCODE_READ_PAGE_SCAN_TYPE                          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_PAGE_SCAN_TYPE_OCF))
#define HCI_COMMAND_OPCODE_WRITE_PAGE_SCAN_TYPE                         (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_PAGE_SCAN_TYPE_OCF))
#define HCI_COMMAND_OPCODE_READ_AFH_CHANNEL_ASSESSMENT_MODE             (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_AFH_CHANNEL_ASSESSMENT_MODE_OCF))
#define HCI_COMMAND_OPCODE_WRITE_AFH_CHANNEL_ASSESSMENT_MODE            (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_AFH_CHANNEL_ASSESSMENT_MODE_OCF))

   /* HCI Command Code OpCode Definitions (Host Control and Baseband -  */
   /* Version 2.1 + EDR).                                               */
#define HCI_COMMAND_OPCODE_READ_EXTENDED_INQUIRY_RESPONSE               (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_EXTENDED_INQUIRY_RESPONSE_OCF))
#define HCI_COMMAND_OPCODE_WRITE_EXTENDED_INQUIRY_RESPONSE              (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_EXTENDED_INQUIRY_RESPONSE_OCF))
#define HCI_COMMAND_OPCODE_REFRESH_ENCRYPTION_KEY                       (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_REFRESH_ENCRYPTION_KEY_OCF))
#define HCI_COMMAND_OPCODE_READ_SIMPLE_PAIRING_MODE                     (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_SIMPLE_PAIRING_MODE_OCF))
#define HCI_COMMAND_OPCODE_WRITE_SIMPLE_PAIRING_MODE                    (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_SIMPLE_PAIRING_MODE_OCF))
#define HCI_COMMAND_OPCODE_READ_LOCAL_OOB_DATA                          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_LOCAL_OOB_DATA_OCF))
#define HCI_COMMAND_OPCODE_READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL   (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL_OCF))
#define HCI_COMMAND_OPCODE_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL           (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL_OCF))
#define HCI_COMMAND_OPCODE_READ_DEFAULT_ERRONEOUS_DATA_REPORTING        (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_DEFAULT_ERRONEOUS_DATA_REPORTING_OCF))
#define HCI_COMMAND_OPCODE_WRITE_DEFAULT_ERRONEOUS_DATA_REPORTING       (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_DEFAULT_ERRONEOUS_DATA_REPORTING_OCF))
#define HCI_COMMAND_OPCODE_ENHANCED_FLUSH                               (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_ENHANCED_FLUSH_OCF))
#define HCI_COMMAND_OPCODE_SEND_KEYPRESS_NOTIFICATION                   (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_SEND_KEYPRESS_NOTIFICATION_OCF))

   /* HCI Command Code OpCode Definitions (Host Control and Baseband -  */
   /* Version 3.0 + HS).                                                */
#define HCI_COMMAND_OPCODE_READ_LOGICAL_LINK_ACCEPT_TIMEOUT             (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_LOGICAL_LINK_ACCEPT_TIMEOUT_OCF))
#define HCI_COMMAND_OPCODE_WRITE_LOGICAL_LINK_ACCEPT_TIMEOUT            (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_LOGICAL_LINK_ACCEPT_TIMEOUT_OCF))
#define HCI_COMMAND_OPCODE_SET_EVENT_MASK_PAGE_2                        (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_SET_EVENT_MASK_PAGE_2_OCF))
#define HCI_COMMAND_OPCODE_READ_LOCATION_DATA                           (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_LOCATION_DATA_OCF))
#define HCI_COMMAND_OPCODE_WRITE_LOCATION_DATA                          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_LOCATION_DATA_OCF))
#define HCI_COMMAND_OPCODE_READ_FLOW_CONTROL_MODE                       (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_FLOW_CONTROL_MODE_OCF))
#define HCI_COMMAND_OPCODE_WRITE_FLOW_CONTROL_MODE                      (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_FLOW_CONTROL_MODE_OCF))
#define HCI_COMMAND_OPCODE_READ_ENHANCED_TRANSMIT_POWER_LEVEL           (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_ENHANCED_TRANSMIT_POWER_LEVEL_OCF))
#define HCI_COMMAND_OPCODE_READ_BEST_EFFORT_FLUSH_TIMEOUT               (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_BEST_EFFORT_FLUSH_TIMEOUT_OCF))
#define HCI_COMMAND_OPCODE_WRITE_BEST_EFFORT_FLUSH_TIMEOUT              (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_BEST_EFFORT_FLUSH_TIMEOUT_OCF))
#define HCI_COMMAND_OPCODE_SHORT_RANGE_MODE                             (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_SHORT_RANGE_MODE_OCF))

   /* HCI Command Code OpCode Definitions (Host Control and Baseband -  */
   /* Version 4.0 + LE).                                                */
#define HCI_COMMAND_OPCODE_READ_LE_HOST_SUPPORTED                       (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_READ_LE_HOST_SUPPORTED_OCF))
#define HCI_COMMAND_OPCODE_WRITE_LE_HOST_SUPPORTED                      (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_WRITE_LE_HOST_SUPPORTED_OCF))
#define HCI_COMMAND_OPCODE_SET_MWS_TRANSPORT_LAYER						(HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_CONTROL_BASEBAND_OGF, HCI_COMMAND_CODE_SET_MWS_TRANSPORT_LAYER_OCF))
 
	 /* HCI Command Code OpCode Definitions (Informational Parameters).   */
#define HCI_COMMAND_OPCODE_READ_LOCAL_VERSION_INFORMATION               (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_INFORMATIONAL_PARAMETERS_OGF, HCI_COMMAND_CODE_READ_LOCAL_VERSION_INFORMATION_OCF))
#define HCI_COMMAND_OPCODE_READ_LOCAL_SUPPORTED_FEATURES                (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_INFORMATIONAL_PARAMETERS_OGF, HCI_COMMAND_CODE_READ_LOCAL_SUPPORTED_FEATURES_OCF))
#define HCI_COMMAND_OPCODE_READ_BUFFER_SIZE                             (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_INFORMATIONAL_PARAMETERS_OGF, HCI_COMMAND_CODE_READ_BUFFER_SIZE_OCF))
#define HCI_COMMAND_OPCODE_READ_COUNTRY_CODE                            (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_INFORMATIONAL_PARAMETERS_OGF, HCI_COMMAND_CODE_READ_COUNTRY_CODE_OCF))
#define HCI_COMMAND_OPCODE_READ_BD_ADDR                                 (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_INFORMATIONAL_PARAMETERS_OGF, HCI_COMMAND_CODE_READ_BD_ADDR_OCF))

   /* HCI Command Code OpCode Definitions (Informational Parameters -   */
   /* Version 1.2).                                                     */
#define HCI_COMMAND_OPCODE_READ_LOCAL_SUPPORTED_COMMANDS                (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_INFORMATIONAL_PARAMETERS_OGF, HCI_COMMAND_CODE_READ_LOCAL_SUPPORTED_COMMANDS_OCF))
#define HCI_COMMAND_OPCODE_READ_LOCAL_EXTENDED_FEATURES                 (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_INFORMATIONAL_PARAMETERS_OGF, HCI_COMMAND_CODE_READ_LOCAL_EXTENDED_FEATURES_OCF))

   /* HCI Command Code OpCode Definitions (Informational Parameters -   */
   /* Version 3.0 + HS).                                                */
#define HCI_COMMAND_OPCODE_READ_DATA_BLOCK_SIZE                         (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_INFORMATIONAL_PARAMETERS_OGF, HCI_COMMAND_CODE_READ_DATA_BLOCK_SIZE_OCF))

   /* HCI Command Code OpCode Definitions (Status Parameters).          */
#define HCI_COMMAND_OPCODE_READ_FAILED_CONTACT_COUNTER                  (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_STATUS_PARAMETERS_OGF, HCI_COMMAND_CODE_READ_FAILED_CONTACT_COUNTER_OCF))
#define HCI_COMMAND_OPCODE_RESET_FAILED_CONTACT_COUNTER                 (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_STATUS_PARAMETERS_OGF, HCI_COMMAND_CODE_RESET_FAILED_CONTACT_COUNTER_OCF))
#define HCI_COMMAND_OPCODE_GET_LINK_QUALITY                             (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_STATUS_PARAMETERS_OGF, HCI_COMMAND_CODE_GET_LINK_QUALITY_OCF))
#define HCI_COMMAND_OPCODE_READ_RSSI                                    (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_STATUS_PARAMETERS_OGF, HCI_COMMAND_CODE_READ_RSSI_OCF))

   /* HCI Command Code OpCode Definitions (Status Parameters - Version  */
   /* 1.2).                                                             */
#define HCI_COMMAND_OPCODE_READ_AFH_CHANNEL_MAP                         (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_STATUS_PARAMETERS_OGF, HCI_COMMAND_CODE_READ_AFH_CHANNEL_MAP_OCF))
#define HCI_COMMAND_OPCODE_READ_CLOCK                                   (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_STATUS_PARAMETERS_OGF, HCI_COMMAND_CODE_READ_CLOCK_OCF))

   /* HCI Command Code OpCode Definitions (Status Parameters - Version  */
   /* 3.0 + HS).                                                        */
#define HCI_COMMAND_OPCODE_READ_ENCRYPTION_KEY_SIZE                     (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_STATUS_PARAMETERS_OGF, HCI_COMMAND_CODE_READ_ENCRYPTION_KEY_SIZE_OCF))
#define HCI_COMMAND_OPCODE_READ_LOCAL_AMP_INFO                          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_STATUS_PARAMETERS_OGF, HCI_COMMAND_CODE_READ_LOCAL_AMP_INFO_OCF))
#define HCI_COMMAND_OPCODE_READ_LOCAL_AMP_ASSOC                         (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_STATUS_PARAMETERS_OGF, HCI_COMMAND_CODE_READ_LOCAL_AMP_ASSOC_OCF))
#define HCI_COMMAND_OPCODE_WRITE_REMOTE_AMP_ASSOC                       (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_STATUS_PARAMETERS_OGF, HCI_COMMAND_CODE_WRITE_REMOTE_AMP_ASSOC_OCF))

   /* HCI Command Code OpCode Definitions (Testing Commands).           */
#define HCI_COMMAND_OPCODE_READ_LOOPBACK_MODE                           (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_TESTING_COMMANDS_OGF, HCI_COMMAND_CODE_READ_LOOPBACK_MODE_OCF))
#define HCI_COMMAND_OPCODE_WRITE_LOOPBACK_MODE                          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_TESTING_COMMANDS_OGF, HCI_COMMAND_CODE_WRITE_LOOPBACK_MODE_OCF))
#define HCI_COMMAND_OPCODE_ENABLE_DEVICE_UNDER_TEST_MODE                (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_TESTING_COMMANDS_OGF, HCI_COMMAND_CODE_ENABLE_DEVICE_UNDER_TEST_MODE_OCF))

   /* HCI Command Code OpCode Definitions (Testing Commands - Version   */
   /* 2.1 + EDR).                                                       */
#define HCI_COMMAND_OPCODE_WRITE_SIMPLE_PAIRING_DEBUG_MODE              (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_TESTING_COMMANDS_OGF, HCI_COMMAND_CODE_WRITE_SIMPLE_PAIRING_DEBUG_MODE_OCF))

   /* HCI Command Code OpCode Definitions (Testing Commands - Version   */
   /* 3.0 + HS).                                                        */
#define HCI_COMMAND_OPCODE_ENABLE_AMP_RECEIVER_REPORTS                  (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_TESTING_COMMANDS_OGF, HCI_COMMAND_CODE_ENABLE_AMP_RECEIVER_REPORTS_OCF))
#define HCI_COMMAND_OPCODE_AMP_TEST_END                                 (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_TESTING_COMMANDS_OGF, HCI_COMMAND_CODE_AMP_TEST_END_OCF))
#define HCI_COMMAND_OPCODE_AMP_TEST                                     (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_TESTING_COMMANDS_OGF, HCI_COMMAND_CODE_AMP_TEST_OCF))

   /* HCI Command Code OpCode Definitions (LE Controller Commands -     */
   /* Version 4.0 + LE).                                                */
#define HCI_COMMAND_OPCODE_LE_SET_EVENT_MASK                            (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_SET_EVENT_MASK_OCF))
#define HCI_COMMAND_OPCODE_LE_READ_BUFFER_SIZE                          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_READ_BUFFER_SIZE_OCF))
#define HCI_COMMAND_OPCODE_LE_READ_LOCAL_SUPPORTED_FEATURES             (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_READ_LOCAL_SUPPORTED_FEATURES_OCF))
#define HCI_COMMAND_OPCODE_LE_SET_RANDOM_ADDRESS                        (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_SET_RANDOM_ADDRESS_OCF))
#define HCI_COMMAND_OPCODE_LE_SET_ADVERTISING_PARAMETERS                (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_SET_ADVERTISING_PARAMETERS_OCF))
#define HCI_COMMAND_OPCODE_LE_READ_ADVERTISING_CHANNEL_TX_POWER         (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_READ_ADVERTISING_CHANNEL_TX_POWER_OCF))
#define HCI_COMMAND_OPCODE_LE_SET_ADVERTISING_DATA                      (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_SET_ADVERTISING_DATA_OCF))
#define HCI_COMMAND_OPCODE_LE_SET_SCAN_RESPONSE_DATA                    (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_SET_SCAN_RESPONSE_DATA_OCF))
#define HCI_COMMAND_OPCODE_LE_SET_ADVERTISE_ENABLE                      (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_SET_ADVERTISE_ENABLE_OCF))
#define HCI_COMMAND_OPCODE_LE_SET_SCAN_PARAMETERS                       (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_SET_SCAN_PARAMETERS_OCF))
#define HCI_COMMAND_OPCODE_LE_SET_SCAN_ENABLE                           (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_SET_SCAN_ENABLE_OCF))
#define HCI_COMMAND_OPCODE_LE_CREATE_CONNECTION                         (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_CREATE_CONNECTION_OCF))
#define HCI_COMMAND_OPCODE_LE_CREATE_CONNECTION_CANCEL                  (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_CREATE_CONNECTION_CANCEL_OCF))
#define HCI_COMMAND_OPCODE_LE_READ_WHITE_LIST_SIZE                      (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_READ_WHITE_LIST_SIZE_OCF))
#define HCI_COMMAND_OPCODE_LE_CLEAR_WHITE_LIST                          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_CLEAR_WHITE_LIST_OCF))
#define HCI_COMMAND_OPCODE_LE_ADD_DEVICE_TO_WHITE_LIST                  (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_ADD_DEVICE_TO_WHITE_LIST_OCF))
#define HCI_COMMAND_OPCODE_LE_REMOVE_DEVICE_FROM_WHITE_LIST             (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_REMOVE_DEVICE_FROM_WHITE_LIST_OCF))
#define HCI_COMMAND_OPCODE_LE_CONNECTION_UPDATE                         (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_CONNECTION_UPDATE_OCF))
#define HCI_COMMAND_OPCODE_LE_SET_HOST_CHANNEL_CLASSIFICATION           (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_SET_HOST_CHANNEL_CLASSIFICATION_OCF))
#define HCI_COMMAND_OPCODE_LE_READ_CHANNEL_MAP                          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_READ_CHANNEL_MAP_OCF))
#define HCI_COMMAND_OPCODE_LE_READ_REMOTE_USED_FEATURES                 (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_READ_REMOTE_USED_FEATURES_OCF))
#define HCI_COMMAND_OPCODE_LE_ENCRYPT                                   (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_ENCRYPT_OCF))
#define HCI_COMMAND_OPCODE_LE_RAND                                      (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_RAND_OCF))
#define HCI_COMMAND_OPCODE_LE_START_ENCRYPTION                          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_START_ENCRYPTION_OCF))
#define HCI_COMMAND_OPCODE_LE_LONG_TERM_KEY_REQUEST_REPLY               (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_LONG_TERM_KEY_REQUEST_REPLY_OCF))
#define HCI_COMMAND_OPCODE_LE_LONG_TERM_KEY_REQUEST_NEGATIVE_REPLY      (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_LONG_TERM_KEY_REQUEST_NEGATIVE_REPLY_OCF))
#define HCI_COMMAND_OPCODE_LE_READ_SUPPORTED_STATES                     (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_READ_SUPPORTED_STATES_OCF))
#define HCI_COMMAND_OPCODE_LE_RECEIVER_TEST                             (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_RECEIVER_TEST_OCF))
#define HCI_COMMAND_OPCODE_LE_TRANSMITTER_TEST                          (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_TRANSMITTER_TEST_OCF))
#define HCI_COMMAND_OPCODE_LE_TEST_END                                  (HCI_MAKE_COMMAND_OPCODE(HCI_COMMAND_CODE_LE_CONTROLLER_COMMANDS_OGF, HCI_COMMAND_CODE_LE_TEST_END_OCF))


   /* HCI Event Declarations/Types/Constants.                           */
#define HCI_EVENT_CODE_INQUIRY_COMPLETE                                 0x01
#define HCI_EVENT_CODE_INQUIRY_RESULT                                   0x02
#define HCI_EVENT_CODE_CONNECTION_COMPLETE                              0x03
#define HCI_EVENT_CODE_CONNECTION_REQUEST                               0x04
#define HCI_EVENT_CODE_DISCONNECTION_COMPLETE                           0x05
#define HCI_EVENT_CODE_AUTHENTICATION_COMPLETE                          0x06
#define HCI_EVENT_CODE_REMOTE_NAME_REQUEST_COMPLETE                     0x07
#define HCI_EVENT_CODE_ENCRYPTION_CHANGE_EVENT                          0x08
#define HCI_EVENT_CODE_CHANGE_CONNECTION_LINK_KEY_COMPLETE              0x09
#define HCI_EVENT_CODE_MASTER_LINK_KEY_COMPLETE                         0x0A
#define HCI_EVENT_CODE_READ_REMOTE_SUPPORTED_FEATURES_COMPLETE          0x0B
#define HCI_EVENT_CODE_READ_REMOTE_VERSION_INFORMATION_COMPLETE         0x0C
#define HCI_EVENT_CODE_QOS_SETUP_COMPLETE                               0x0D
#define HCI_EVENT_CODE_COMMAND_COMPLETE                                 0x0E
#define HCI_EVENT_CODE_COMMAND_STATUS                                   0x0F
#define HCI_EVENT_CODE_HARDWARE_ERROR                                   0x10
#define HCI_EVENT_CODE_FLUSH_OCCURRED                                   0x11
#define HCI_EVENT_CODE_ROLE_CHANGE                                      0x12
#define HCI_EVENT_CODE_NUMBER_OF_COMPLETED_PACKETS                      0x13
#define HCI_EVENT_CODE_MODE_CHANGE                                      0x14
#define HCI_EVENT_CODE_RETURN_LINK_KEYS                                 0x15
#define HCI_EVENT_CODE_PIN_CODE_REQUEST                                 0x16
#define HCI_EVENT_CODE_LINK_KEY_REQUEST                                 0x17
#define HCI_EVENT_CODE_LINK_KEY_NOTIFICATION                            0x18
#define HCI_EVENT_CODE_LOOPBACK_COMMAND                                 0x19
#define HCI_EVENT_CODE_DATA_BUFFER_OVERFLOW                             0x1A
#define HCI_EVENT_CODE_MAX_SLOTS_CHANGE_EVENT                           0x1B
#define HCI_EVENT_CODE_READ_CLOCK_OFFSET_COMPLETE                       0x1C
#define HCI_EVENT_CODE_CONNECTION_PACKET_TYPE_CHANGED                   0x1D
#define HCI_EVENT_CODE_QOS_VIOLATION                                    0x1E
#define HCI_EVENT_CODE_PAGE_SCAN_MODE_CHANGE                            0x1F
#define HCI_EVENT_CODE_PAGE_SCAN_REPETITION_MODE_CHANGE                 0x20

#define HCI_EVENT_CODE_BLUETOOTH_LOGO_TESTING                           0xFE
#define HCI_EVENT_CODE_VENDOR_SPECIFIC_DEBUG                            0xFF

   /* The following block of HCI Event Declarations/Type/Constants are  */
   /* for Version 1.2.                                                  */
#define HCI_EVENT_CODE_FLOW_SPECIFICATION_COMPLETE                      0x21
#define HCI_EVENT_CODE_INQUIRY_RESULT_WITH_RSSI                         0x22
#define HCI_EVENT_CODE_READ_REMOTE_EXTENDED_FEATURES_COMPLETE           0x23
#define HCI_EVENT_CODE_SYNCHRONOUS_CONNECTION_COMPLETE                  0x2C
#define HCI_EVENT_CODE_SYNCHRONOUS_CONNECTION_CHANGED                   0x2D

   /* The following block of HCI Event Declarations/Type/Constants are  */
   /* for Version 2.1 + EDR.                                            */
#define HCI_EVENT_CODE_SNIFF_SUBRATING                                  0x2E
#define HCI_EVENT_CODE_EXTENDED_INQUIRY_RESULT                          0x2F
#define HCI_EVENT_CODE_ENCRYPTION_KEY_REFRESH_COMPLETE                  0x30
#define HCI_EVENT_CODE_IO_CAPABILITY_REQUEST                            0x31
#define HCI_EVENT_CODE_IO_CAPABILITY_RESPONSE                           0x32
#define HCI_EVENT_CODE_USER_CONFIRMATION_REQUEST                        0x33
#define HCI_EVENT_CODE_USER_PASSKEY_REQUEST                             0x34
#define HCI_EVENT_CODE_REMOTE_OOB_DATA_REQUEST                          0x35
#define HCI_EVENT_CODE_SIMPLE_PAIRING_COMPLETE                          0x36
#define HCI_EVENT_CODE_LINK_SUPERVISION_TIMEOUT_CHANGED                 0x38
#define HCI_EVENT_CODE_ENHANCED_FLUSH_COMPLETE                          0x39
#define HCI_EVENT_CODE_USER_PASSKEY_NOTIFICATION                        0x3B
#define HCI_EVENT_CODE_KEYPRESS_NOTIFICATION                            0x3C
#define HCI_EVENT_CODE_REMOTE_HOST_SUPPORTED_FEATURES_NOTIFICATION      0x3D

   /* The following block of HCI Event Declarations/Type/Constants are  */
   /* for Version 3.0 + HS.                                             */
#define HCI_EVENT_CODE_PHYSICAL_LINK_COMPLETE                           0x40
#define HCI_EVENT_CODE_CHANNEL_SELECTED                                 0x41
#define HCI_EVENT_CODE_DISCONNECTION_PHYSICAL_LINK_COMPLETE             0x42
#define HCI_EVENT_CODE_PHYSICAL_LINK_LOSS_EARLY_WARNING                 0x43
#define HCI_EVENT_CODE_PHYSICAL_LINK_RECOVERY                           0x44
#define HCI_EVENT_CODE_LOGICAL_LINK_COMPLETE                            0x45
#define HCI_EVENT_CODE_DISCONNECTION_LOGICAL_LINK_COMPLETE              0x46
#define HCI_EVENT_CODE_FLOW_SPEC_MODIFY_COMPLETE                        0x47
#define HCI_EVENT_CODE_NUMBER_OF_COMPLETED_DATA_BLOCKS                  0x48
#define HCI_EVENT_CODE_AMP_START_TEST                                   0x49
#define HCI_EVENT_CODE_AMP_TEST_END                                     0x4A
#define HCI_EVENT_CODE_AMP_RECEIVER_REPORT                              0x4B
#define HCI_EVENT_CODE_SHORT_RANGE_MODE_CHANGE_COMPLETE                 0x4C
#define HCI_EVENT_CODE_AMP_STATUS_CHANGE                                0x4D

   /* The following block of HCI Event Declarations/Type/Constants are  */
   /* for Version 4.0 + LE.                                             */
   /* * NOTE * All Bluetooth Low Energy (LE) events are grouped under a */
   /*          single event called the Meta event.  The Meta event      */
   /*          contains a Sub Event Code that actually specifies the    */
   /*          Bluetooth Low Energy (LE) event code.                    */
#define HCI_EVENT_CODE_LE_META                                          0x3E

   /* The following constants represent the maximum palyload sizes that */
   /* are possible for each packet type.                                */
#define HCI_PACKET_TYPE_DM1_MAXIMUM_PAYLOAD_SIZE                          17
#define HCI_PACKET_TYPE_DH1_MAXIMUM_PAYLOAD_SIZE                          27
#define HCI_PACKET_TYPE_DM3_MAXIMUM_PAYLOAD_SIZE                         121
#define HCI_PACKET_TYPE_DH3_MAXIMUM_PAYLOAD_SIZE                         183
#define HCI_PACKET_TYPE_DM5_MAXIMUM_PAYLOAD_SIZE                         224
#define HCI_PACKET_TYPE_DH5_MAXIMUM_PAYLOAD_SIZE                         339
#define HCI_PACKET_TYPE_AUX1_MAXIMUM_PAYLOAD_SIZE                         29
#define HCI_PACKET_TYPE_2_DH1_MAXIMUM_PAYLOAD_SIZE                        54
#define HCI_PACKET_TYPE_2_DH3_MAXIMUM_PAYLOAD_SIZE                       367
#define HCI_PACKET_TYPE_2_DH5_MAXIMUM_PAYLOAD_SIZE                       679
#define HCI_PACKET_TYPE_3_DH1_MAXIMUM_PAYLOAD_SIZE                        83
#define HCI_PACKET_TYPE_3_DH3_MAXIMUM_PAYLOAD_SIZE                       552
#define HCI_PACKET_TYPE_3_DH5_MAXIMUM_PAYLOAD_SIZE                      1021

#define HCI_PACKET_TYPE_HV1_MAXIMUM_PAYLOAD_SIZE                          10
#define HCI_PACKET_TYPE_HV2_MAXIMUM_PAYLOAD_SIZE                          20
#define HCI_PACKET_TYPE_HV3_MAXIMUM_PAYLOAD_SIZE                          30
#define HCI_PACKET_TYPE_DV_MAXIMUM_PAYLOAD_SIZE                           29
#define HCI_PACKET_TYPE_EV3_MAXIMUM_PAYLOAD_SIZE                          30
#define HCI_PACKET_TYPE_EV4_MAXIMUM_PAYLOAD_SIZE                         120
#define HCI_PACKET_TYPE_EV5_MAXIMUM_PAYLOAD_SIZE                         180
#define HCI_PACKET_TYPE_2_EV3_MAXIMUM_PAYLOAD_SIZE                       192
#define HCI_PACKET_TYPE_2_EV5_MAXIMUM_PAYLOAD_SIZE                       576
#define HCI_PACKET_TYPE_3_EV3_MAXIMUM_PAYLOAD_SIZE                       288
#define HCI_PACKET_TYPE_3_EV5_MAXIMUM_PAYLOAD_SIZE                       864



/* The following Constants represent the defined Bluetooth HCI Simple*/
/* Pairing Modes (Version 2.1 + EDR).                                */
#define HCI_SIMPLE_PAIRING_MODE_NOT_ENABLED                             0x00
#define HCI_SIMPLE_PAIRING_MODE_ENABLED                                 0x01

/* The following Constants represent the defined Bluetooth HCI Scan  */
/* Enable Types.                                                     */
#define HCI_SCAN_ENABLE_NO_SCANS_ENABLED                                0x00
#define HCI_SCAN_ENABLE_INQUIRY_SCAN_ENABLED_PAGE_SCAN_DISABLED         0x01
#define HCI_SCAN_ENABLE_INQUIRY_SCAN_DISABLED_PAGE_SCAN_ENABLED         0x02
#define HCI_SCAN_ENABLE_INQUIRY_SCAN_ENABLED_PAGE_SCAN_ENABLED          0x03

#define HCI_SCAN_ENABLE_INQUIRY_SCAN_ENABLED_BIT_MASK                   0x01
#define HCI_SCAN_ENABLE_PAGE_SCAN_ENABLED_BIT_MASK                      0x02



#endif //_HCI_CONSTANTSH